import {
  transformerNotationHighlight,
  transformerNotationFocus,
  transformerMetaHighlight,
  transformerNotationDiff,
} from '@shikijs/transformers';
import type { ShikiTransformer } from '@shikijs/types';
import { createCssVariablesTheme } from 'shiki/core';
import type { BundledLanguage, ThemeRegistration } from 'shiki/types';

export const LINE_HIGHLIGHT_CLASS_NAME = 'line-highlight';
export const LINE_FOCUS_CLASS_NAME = 'line-focus';
export const LINE_DIFF_ADD_CLASS_NAME = 'line-diff line-add';
export const LINE_DIFF_REMOVE_CLASS_NAME = 'line-diff line-remove';

export type ShikiLang = BundledLanguage | 'text';
export type ShikiTheme = (typeof SHIKI_THEMES)[number];

export const SHIKI_CSS_THEME = createCssVariablesTheme({
  name: 'css-variables',
  variablePrefix: '--mint-',
  variableDefaults: {
    'color-text': '#171717',
    'color-background': 'transparent',
    'token-constant': '#171717',
    'token-string': '#297a3a',
    'token-comment': '#666666',
    'token-keyword': '#bd2864',
    'token-parameter': '#a35200',
    'token-function': '#0068d6',
    'token-string-expression': '#297a3a',
    'token-punctuation': '#171717',
    'token-link': '#297a3a',

    'ansi-black': '#000000',
    'ansi-black-dim': '#00000080',
    'ansi-red': '#bb0000',
    'ansi-red-dim': '#bb000080',
    'ansi-green': '#00bb00',
    'ansi-green-dim': '#00bb0080',
    'ansi-yellow': '#bbbb00',
    'ansi-yellow-dim': '#bbbb0080',
    'ansi-blue': '#0000bb',
    'ansi-blue-dim': '#0000bb80',
    'ansi-magenta': '#ff00ff',
    'ansi-magenta-dim': '#ff00ff80',
    'ansi-cyan': '#00bbbb',
    'ansi-cyan-dim': '#00bbbb80',
    'ansi-white': '#eeeeee',
    'ansi-white-dim': '#eeeeee80',
    'ansi-bright-black': '#555555',
    'ansi-bright-black-dim': '#55555580',
    'ansi-bright-red': '#ff5555',
    'ansi-bright-red-dim': '#ff555580',
    'ansi-bright-green': '#00ff00',
    'ansi-bright-green-dim': '#00ff0080',
    'ansi-bright-yellow': '#ffff55',
    'ansi-bright-yellow-dim': '#ffff5580',
    'ansi-bright-blue': '#5555ff',
    'ansi-bright-blue-dim': '#5555ff80',
    'ansi-bright-magenta': '#ff55ff',
    'ansi-bright-magenta-dim': '#ff55ff80',
    'ansi-bright-cyan': '#55ffff',
    'ansi-bright-cyan-dim': '#55ffff80',
    'ansi-bright-white': '#ffffff',
    'ansi-bright-white-dim': '#ffffff80',
  },
  fontStyle: true,
});

export const DEFAULT_LANG = 'text' as const;
export const DEFAULT_DARK_THEME: ShikiTheme = 'dark-plus' as const;
export const DEFAULT_LIGHT_THEME: ShikiTheme = 'github-light-default' as const;
export const DEFAULT_THEMES: [ShikiTheme, ShikiTheme, ThemeRegistration] = [
  DEFAULT_LIGHT_THEME,
  DEFAULT_DARK_THEME,
  SHIKI_CSS_THEME,
] as const;

export const shikiColorReplacements: Partial<Record<ShikiTheme, string | Record<string, string>>> =
  {
    'dark-plus': {
      '#1e1e1e': 'transparent',
      '#569cd6': '#9cdcfe',
      '#c8c8c8': '#f3f7f6',
      '#d4d4d4': '#f3f7f6',
    },
    'github-light-default': {
      '#fff': 'transparent',
      '#ffffff': 'transparent',
    },
  };

export const DEFAULT_LANG_ALIASES: Record<string, ShikiLang> = {
  abap: 'abap',
  'actionscript-3': 'actionscript-3',
  ada: 'ada',
  'angular-html': 'angular-html',
  'angular-ts': 'angular-ts',
  apache: 'apache',
  apex: 'apex',
  apl: 'apl',
  applescript: 'applescript',
  ara: 'ara',
  asciidoc: 'asciidoc',
  adoc: 'asciidoc',
  asm: 'asm',
  astro: 'astro',
  awk: 'awk',
  ballerina: 'ballerina',
  bat: 'bat',
  batch: 'bat',
  beancount: 'beancount',
  berry: 'berry',
  be: 'berry',
  bibtex: 'bibtex',
  bicep: 'bicep',
  blade: 'blade',
  bsl: 'bsl',
  '1c': 'bsl',
  c: 'c',
  h: 'c',
  cadence: 'cadence',
  cdc: 'cadence',
  cairo: 'cairo',
  clarity: 'clarity',
  clojure: 'clojure',
  clj: 'clojure',
  cmake: 'cmake',
  cobol: 'cobol',
  codeowners: 'codeowners',
  codeql: 'codeql',
  ql: 'codeql',
  coffee: 'coffee',
  coffeescript: 'coffee',
  'common-lisp': 'common-lisp',
  lisp: 'common-lisp',
  coq: 'coq',
  cpp: 'cpp',
  cc: 'cpp',
  hh: 'cpp',
  'c++': 'cpp',
  crystal: 'crystal',
  csharp: 'csharp',
  'c#': 'csharp',
  cs: 'csharp',
  css: 'css',
  csv: 'csv',
  cue: 'cue',
  cypher: 'cypher',
  cql: 'cypher',
  d: 'd',
  dart: 'dart',
  dax: 'dax',
  desktop: 'desktop',
  diff: 'diff',
  docker: 'docker',
  dockerfile: 'docker',
  dotenv: 'dotenv',
  'dream-maker': 'dream-maker',
  edge: 'edge',
  elixir: 'elixir',
  elm: 'elm',
  'emacs-lisp': 'emacs-lisp',
  elisp: 'emacs-lisp',
  erb: 'erb',
  erlang: 'erlang',
  erl: 'erlang',
  fennel: 'fennel',
  fish: 'fish',
  fluent: 'fluent',
  ftl: 'fluent',
  'fortran-fixed-form': 'fortran-fixed-form',
  f: 'fortran-fixed-form',
  for: 'fortran-fixed-form',
  f77: 'fortran-fixed-form',
  'fortran-free-form': 'fortran-free-form',
  f90: 'fortran-free-form',
  f95: 'fortran-free-form',
  f03: 'fortran-free-form',
  f08: 'fortran-free-form',
  f18: 'fortran-free-form',
  fsharp: 'fsharp',
  'f#': 'fsharp',
  fs: 'fsharp',
  gdresource: 'gdresource',
  gdscript: 'gdscript',
  gdshader: 'gdshader',
  genie: 'genie',
  gherkin: 'gherkin',
  'git-commit': 'git-commit',
  'git-rebase': 'git-rebase',
  gleam: 'gleam',
  'glimmer-js': 'glimmer-js',
  gjs: 'glimmer-js',
  'glimmer-ts': 'glimmer-ts',
  gts: 'glimmer-ts',
  glsl: 'glsl',
  gnuplot: 'gnuplot',
  go: 'go',
  graphql: 'graphql',
  gql: 'graphql',
  groovy: 'groovy',
  hack: 'hack',
  haml: 'haml',
  handlebars: 'handlebars',
  hbs: 'handlebars',
  haskell: 'haskell',
  hs: 'haskell',
  haxe: 'haxe',
  hcl: 'hcl',
  hjson: 'hjson',
  hlsl: 'hlsl',
  html: 'html',
  'html-derivative': 'html-derivative',
  http: 'http',
  hxml: 'hxml',
  hy: 'hy',
  imba: 'imba',
  ini: 'ini',
  properties: 'ini',
  java: 'java',
  javascript: 'javascript',
  js: 'javascript',
  jinja: 'jinja',
  jison: 'jison',
  json: 'json',
  json5: 'json5',
  jsonc: 'jsonc',
  jsonl: 'jsonl',
  jsonnet: 'jsonnet',
  jssm: 'jssm',
  fsl: 'jssm',
  jsx: 'jsx',
  julia: 'julia',
  jl: 'julia',
  kotlin: 'kotlin',
  kt: 'kotlin',
  kts: 'kotlin',
  kusto: 'kusto',
  kql: 'kusto',
  latex: 'latex',
  lean: 'lean',
  lean4: 'lean',
  less: 'less',
  liquid: 'liquid',
  llvm: 'llvm',
  log: 'log',
  logo: 'logo',
  lua: 'lua',
  luau: 'luau',
  make: 'make',
  makefile: 'make',
  markdown: 'markdown',
  md: 'markdown',
  marko: 'marko',
  matlab: 'matlab',
  mdc: 'mdc',
  mdx: 'mdx',
  mermaid: 'mermaid',
  mmd: 'mermaid',
  mipsasm: 'mipsasm',
  mips: 'mipsasm',
  mojo: 'mojo',
  move: 'move',
  narrat: 'narrat',
  nar: 'narrat',
  nextflow: 'nextflow',
  nf: 'nextflow',
  nginx: 'nginx',
  nim: 'nim',
  nix: 'nix',
  nushell: 'nushell',
  nu: 'nushell',
  'objective-c': 'objective-c',
  objc: 'objective-c',
  'objective-cpp': 'objective-cpp',
  ocaml: 'ocaml',
  pascal: 'pascal',
  perl: 'perl',
  php: 'php',
  plsql: 'plsql',
  po: 'po',
  pot: 'po',
  potx: 'po',
  polar: 'polar',
  postcss: 'postcss',
  powerquery: 'powerquery',
  powershell: 'powershell',
  ps: 'powershell',
  ps1: 'powershell',
  prisma: 'prisma',
  prolog: 'prolog',
  proto: 'proto',
  protobuf: 'proto',
  pug: 'pug',
  jade: 'pug',
  puppet: 'puppet',
  purescript: 'purescript',
  python: 'python',
  py: 'python',
  qml: 'qml',
  qmldir: 'qmldir',
  qss: 'qss',
  r: 'r',
  racket: 'racket',
  raku: 'raku',
  perl6: 'raku',
  razor: 'razor',
  reg: 'reg',
  regexp: 'regexp',
  regex: 'regexp',
  rel: 'rel',
  riscv: 'riscv',
  rst: 'rst',
  ruby: 'ruby',
  rb: 'ruby',
  rust: 'rust',
  rs: 'rust',
  sas: 'sas',
  sass: 'sass',
  scala: 'scala',
  scheme: 'scheme',
  scss: 'scss',
  sdbl: 'sdbl',
  '1c-query': 'sdbl',
  shaderlab: 'shaderlab',
  shader: 'shaderlab',
  shellscript: 'shellscript',
  bash: 'shellscript',
  sh: 'shellscript',
  shell: 'shellscript',
  zsh: 'shellscript',
  shellsession: 'shellsession',
  console: 'shellsession',
  smalltalk: 'smalltalk',
  solidity: 'solidity',
  soy: 'soy',
  'closure-templates': 'soy',
  sparql: 'sparql',
  splunk: 'splunk',
  spl: 'splunk',
  sql: 'sql',
  'ssh-config': 'ssh-config',
  stata: 'stata',
  stylus: 'stylus',
  styl: 'stylus',
  svelte: 'svelte',
  swift: 'swift',
  'system-verilog': 'system-verilog',
  systemd: 'systemd',
  talonscript: 'talonscript',
  talon: 'talonscript',
  tasl: 'tasl',
  tcl: 'tcl',
  templ: 'templ',
  terraform: 'terraform',
  tf: 'terraform',
  tfvars: 'terraform',
  tex: 'tex',
  toml: 'toml',
  'ts-tags': 'ts-tags',
  lit: 'ts-tags',
  tsv: 'tsv',
  tsx: 'tsx',
  turtle: 'turtle',
  twig: 'twig',
  typescript: 'typescript',
  ts: 'typescript',
  typespec: 'typespec',
  tsp: 'typespec',
  typst: 'typst',
  typ: 'typst',
  txt: 'text',
  text: 'text',
  plaintext: 'text',
  plain: 'text',
  v: 'v',
  vala: 'vala',
  vb: 'vb',
  cmd: 'vb',
  verilog: 'verilog',
  vhdl: 'vhdl',
  viml: 'viml',
  vim: 'viml',
  vimscript: 'viml',
  vue: 'vue',
  'vue-html': 'vue-html',
  vyper: 'vyper',
  vy: 'vyper',
  wasm: 'wasm',
  wenyan: 'wenyan',
  文言: 'wenyan',
  wgsl: 'wgsl',
  wikitext: 'wikitext',
  mediawiki: 'wikitext',
  wiki: 'wikitext',
  wit: 'wit',
  wolfram: 'wolfram',
  wl: 'wolfram',
  xml: 'xml',
  xsl: 'xsl',
  yaml: 'yaml',
  yml: 'yaml',
  zenscript: 'zenscript',
  zig: 'zig',
};

export const UNIQUE_LANGS = Array.from(new Set(Object.values(DEFAULT_LANG_ALIASES)));

export const SHIKI_THEMES = [
  'andromeeda',
  'aurora-x',
  'ayu-dark',
  'catppuccin-frappe',
  'catppuccin-latte',
  'catppuccin-macchiato',
  'catppuccin-mocha',
  'dark-plus',
  'dracula',
  'dracula-soft',
  'everforest-dark',
  'everforest-light',
  'github-dark',
  'github-dark-default',
  'github-dark-dimmed',
  'github-dark-high-contrast',
  'github-light',
  'github-light-default',
  'github-light-high-contrast',
  'gruvbox-dark-hard',
  'gruvbox-dark-medium',
  'gruvbox-dark-soft',
  'gruvbox-light-hard',
  'gruvbox-light-medium',
  'gruvbox-light-soft',
  'houston',
  'kanagawa-dragon',
  'kanagawa-lotus',
  'kanagawa-wave',
  'laserwave',
  'light-plus',
  'material-theme',
  'material-theme-darker',
  'material-theme-lighter',
  'material-theme-ocean',
  'material-theme-palenight',
  'min-dark',
  'min-light',
  'monokai',
  'night-owl',
  'nord',
  'one-dark-pro',
  'one-light',
  'plastic',
  'poimandres',
  'red',
  'rose-pine',
  'rose-pine-dawn',
  'rose-pine-moon',
  'slack-dark',
  'slack-ochin',
  'snazzy-light',
  'solarized-dark',
  'solarized-light',
  'synthwave-84',
  'tokyo-night',
  'vesper',
  'vitesse-black',
  'vitesse-dark',
  'vitesse-light',

  'css-variables', // for users who want to use custom CSS to style their code blocks
] as const;

export const DEFAULT_LANGS = [
  'bash',
  'blade',
  'c',
  'css',
  'c#',
  'c++',
  'dart',
  'diff',
  'go',
  'html',
  'java',
  'javascript',
  'jsx',
  'json',
  'kotlin',
  'log',
  'lua',
  'markdown',
  'mdx',
  'php',
  'powershell',
  'python',
  'ruby',
  'rust',
  'solidity',
  'swift',
  'toml',
  'typescript',
  'tsx',
  'yaml',
];

export const matchAlgorithm = {
  matchAlgorithm: 'v3',
} as const;

export const SHIKI_TRANSFORMERS: ShikiTransformer[] = [
  transformerMetaHighlight({
    className: LINE_HIGHLIGHT_CLASS_NAME,
  }),
  transformerNotationHighlight({
    ...matchAlgorithm,
    classActiveLine: LINE_HIGHLIGHT_CLASS_NAME,
  }),
  transformerNotationFocus({
    ...matchAlgorithm,
    classActiveLine: LINE_FOCUS_CLASS_NAME,
  }),
  transformerNotationDiff({
    ...matchAlgorithm,
    classLineAdd: LINE_DIFF_ADD_CLASS_NAME,
    classLineRemove: LINE_DIFF_REMOVE_CLASS_NAME,
  }),
];
